Intake band updates
Overture-7421/HayabusaRobotCode_23619 pull request #13
Opened 2024-01-18 23:44 UTC by MarcoAlejandroLopezGomez

Before issuing a pull request, please see the contributing page.

2024-01-18 23:49 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/MoveShooter.java
> +    public MoveShooter(Shooter subsystem, double voltage) {
Not a voltage

2024-01-18 23:49 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/MoveShooter.java
> +        shooter.Voltage(voltage);
Not a voltage

2024-01-18 23:49 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainSystem.java
> +        intake      = new Intake(hardwareMap, "intake");      // Create an instance of Intake
Inside the Intake Subsystem

2024-01-18 23:49 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Shooter.java
> +    public void Voltage(double ShooterMotorPosition) {
Change

2024-01-18 23:49 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Intake.java
> +            intake = hMap.get(DcMotor.class, IntakeSubsystem);
Fix

2024-01-18 23:57 UTC, MarcoAlejandroLopezGomez commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/MoveShooter.java
> +    public MoveShooter(Shooter subsystem, double voltage) {
Fix

2024-01-18 23:57 UTC, MarcoAlejandroLopezGomez commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/MoveShooter.java
> +        shooter.Voltage(voltage);
Fix

2024-01-18 23:57 UTC, MarcoAlejandroLopezGomez commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainSystem.java
> +        intake      = new Intake(hardwareMap, "intake");      // Create an instance of Intake
Fix

2024-01-18 23:57 UTC, MarcoAlejandroLopezGomez commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Shooter.java
> +    public void Voltage(double ShooterMotorPosition) {
Fix

2024-01-18 23:58 UTC, MarcoAlejandroLopezGomez commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Intake.java
> +            intake = hMap.get(DcMotor.class, IntakeSubsystem);
Fix

2024-01-19 00:02 UTC, SantiQ0905 requested changes

2024-01-19 00:02 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Intake.java
> +            intake = hardwareMap.get(DcMotor.class, "IntakeSubsystem");
Not the name of the motor

2024-01-19 00:04 UTC, MarcoAlejandroLopezGomez commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Intake.java
> +            intake = hardwareMap.get(DcMotor.class, "IntakeSubsystem");
Fix

2024-01-19 00:09 UTC, SantiQ0905 approved these changes

2024-01-19 00:09 UTC, merged