All of the Autonomous that are NOT basic work, fixed the arm and the …
Overture-7421/HayabusaRobotCode_23619 pull request #28
Opened 2024-01-27 20:03 UTC by Drfeelgood999

…claw

Before issuing a pull request, please see the contributing page.

2024-01-27 21:06 UTC, SantiQ0905 requested changes

2024-01-27 21:06 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBasicLeft.java
Does the intake has had any issue while spitting the pixels with this Timeout?

2024-01-27 21:06 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBasicRight.java
Same as the other comment.

2024-01-27 21:06 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBlueTop.java
Consider adding another waypoint some centimetres back so that the pixels can be spitted easier.

2024-01-27 21:06 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousRedTop.java
Have you updated the Notion regarding this Autonomous?

2024-01-27 21:06 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Commands/MoveArm.java
Excellent work on the arm, the video shows it works splendid.

2024-01-27 21:06 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainSystem.java
What was the Method that changed for the Claw and Arm. Mr. Leyva has told me he gave you some feedback.

2024-01-27 21:06 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Arm.java
Why are you multiplying by -1?

2024-01-27 21:09 UTC, Drfeelgood999 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBasicLeft.java
Nein, es ist alles gut :)

2024-01-27 21:10 UTC, Drfeelgood999 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousRedTop.java
Yes

2024-01-27 21:11 UTC, Drfeelgood999 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainSystem.java
Its called "rotate by", however we didn't add this method to the claw since it already worked before, just for the arm

2024-01-27 21:12 UTC, Drfeelgood999 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Arm.java
So that both of motors go the same direction, functions as a REVERSE

2024-01-27 21:13 UTC, Drfeelgood999 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBlueTop.java
OK

2024-01-27 21:13 UTC, Drfeelgood999 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBasicRight.java
The intake is alright, we just need to fix the trajectory

2024-01-28 01:50 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBasicLeft.java
Alright!

2024-01-28 01:50 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainSystem.java
Excellent.

2024-01-28 01:50 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainSystem.java
> +import static android.opengl.ETC1.getHeight;
What is this for?

2024-01-28 01:50 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainSystem.java
> +            telemetry.addData("Elevator 1 Height", elevator.elevatorMotor1getCurrentHeight());
What has changed for the elevator?

2024-01-28 01:50 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Elevator.java
Interesting. Does it work?

2024-01-28 22:08 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBasicRight.java
Cool

2024-01-28 22:08 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousBlueTop.java
Alright!

2024-01-28 22:09 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousRedTop.java
Excellent

2024-01-28 22:09 UTC, SantiQ0905 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Subsystems/Arm.java
Great!

2024-01-28 22:35 UTC, SantiQ0905 approved these changes

2024-01-28 22:36 UTC, merged